name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Access Secrets from AWS Secret Manager
        id: get_secrets
        run: |
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id dataloader --query SecretString --output text)
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd dataloader
            git pull origin master
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> .env
            echo "EC2_USER=${{ secrets.EC2_USER }}" >> .env
            echo "EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}" >> .env
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
            docker-compose down
            docker-compose up -d --build
